[deps]
ArgumentProcessor = "da5e4181-4678-44ac-9e93-56ca85e03b1f"
DWN = "cd0201ce-641d-4930-81fb-47a2ab5929d7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaSourceMechanism = "fcf89f7a-9a65-42c5-bcc0-284547580d60"
LengthAreaVolume = "efc29244-82b9-40dc-80c2-83e112b54aab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SeisTools = "1a3a5297-0f7d-450c-8955-231a439346a8"
SeismicRayTrace = "1a90cdcd-02e0-4887-85dc-4804a62d2cac"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[sources]
ArgumentProcessor = {rev = "main", url = "https://gitee.com/changguo1998/ArgumentProcessor.jl"}
DWN = {rev = "master", url = "https://gitee.com/changguo1998/DWN.jl"}
JuliaSourceMechanism = {rev = "master", url = "https://gitee.com/changguo1998/JuliaSourceMechanism.jl"}
LengthAreaVolume = {rev = "master", url = "https://gitee.com/changguo1998/LengthAreaVolume.jl"}
SeisTools = {rev = "develop", url = "https://gitee.com/changguo1998/SeisTools.jl"}
SeismicRayTrace = {rev = "main", url = "https://gitee.com/changguo1998/SeismicRayTrace.jl"}
