update_date = 2025-12-03

[[server]]
hostname = "Room309"
ip = "localhost"
user = "guochang"
system_root = "/home/guochang/Projects/distributed-fm-inverse"
max_event_number = 1
threads_per_event = 32
priority = 2

[host]
hostname = "Room309"
ip = "localhost"
user = "guochang"
system_root = "/home/guochang/Projects/distributed-fm-inverse"
monitor_directory = [
    "/home/guochang/Projects/distributed-fm-inverse/test/monitored_dir",
    "/data/real_time_system_data/db_v1/fm"
]
