update_date = 2025-12-10

[[server]]
hostname = "PowerEdge1"
ip = "210.45.127.110"
user = "guochang"
system_root = "/data2/guochang/distributed-fm-inverse"
max_event_number = 4
threads_per_event = 32
priority = 1

[[server]]
hostname = "PowerEdge2"
ip = "210.45.127.108"
user = "guochang"
system_root = "/data2/guochang/distributed-fm-inverse"
max_event_number = 4
threads_per_event = 32
priority = 1

[[server]]
hostname = "PowerEdge3"
ip = "210.45.127.112"
user = "guochang"
system_root = "/data2/guochang/distributed-fm-inverse"
max_event_number = 4
threads_per_event = 32
priority = 2

[[server]]
hostname = "PowerEdge4"
ip = "210.45.127.117"
user = "guochang"
system_root = "/data/guochang/distributed-fm-inverse"
max_event_number = 4
threads_per_event = 32
priority = 2

[[server]]
hostname = "PowerEdge5"
ip = "222.195.83.19"
user = "guochang"
system_root = "/data/guochang/distributed-fm-inverse"
max_event_number = 2
threads_per_event = 32
priority = 2

[[server]]
hostname = "Room309"
ip = "localhost"
user = "guochang"
system_root = "/home/guochang/Projects/distributed-fm-inverse"
max_event_number = 1
threads_per_event = 32
priority = 2

[host]
hostname = "Room309"
monitor_directory = [
    "/home/guochang/Projects/distributed-fm-inverse/test/monitored_dir",
    "/data/real_time_system_data/db_v1/fm"
]
