update_date = 2025-12-03

[[server]]
hostname = "PowerEdge3"
ip = "210.45.127.112"
user = "guochang"
system_root = "/data2/guochang/distributed-fm-inverse"
max_event_number = 4
threads_per_event = 32
priority = 2

[[server]]
hostname = "PowerEdge4"
ip = "210.45.127.117"
user = "guochang"
system_root = "/data/guochang/distributed-fm-inverse"
max_event_number = 3
threads_per_event = 32
priority = 2

[host]
hostname = "Room309"
ip = "localhost"
user = "guochang"
system_root = "/home/guochang/Projects/distributed-fm-inverse"
monitor_directory = [
    "/home/guochang/Projects/distributed-fm-inverse/test/monitored_dir",
    "/data/real_time_system_data/db_v1/fm"
]
